Add some basic instructions for create the customization yaml file
CartoDB/carto-selfhosted-helm pull request #155
Opened 2022-06-07 09:49 UTC by alvarorm22

**Description of the change**

Add some basic instructions for create the customization yaml file

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

2022-06-07 10:02 UTC, aitorch approved these changes
LGTM

2022-06-07 13:41 UTC, jvillarf requested changes
Additionally, please as @ManuelLR suggested, let's consolidate these instructions with https://github.com/CartoDB/carto-selfhosted-helm/pull/155/files#diff-22be7b2163c32925f5228017d7eabef17cd467eca5b56e7923a0541bf129edb0R23-R39

2022-06-07 13:41 UTC, jvillarf commented on customizations/README.md
> +- The configuration file `customizations.yaml` will be composed with keys and their value, please do not define the same key several times, because they will be overrided between them. Each key in th
`s/overrided/overridden/`

2022-06-07 13:41 UTC, jvillarf commented on customizations/README.md
> +- Check the text values of the `customizations.yaml` keys, they have to be setted between quotes. Example:
`s/setted/set/`

2022-06-07 13:41 UTC, jvillarf commented on customizations/README.md
> +  Note that integers and booleans values are setted without quotes.
`s/setted/set/`

2022-06-08 14:33 UTC, miguelangelmorenochacon commented on customizations/README.md
> +## Tips for create the customization Yaml file
tips for _creating_

2022-06-08 14:34 UTC, miguelangelmorenochacon commented on customizations/README.md
> +- The configuration file `customizations.yaml` will be composed with keys and their value, please do not define the same key several times, because they will be overridden between them. Each key in t
composed _with_ keys

2022-06-08 14:34 UTC, miguelangelmorenochacon commented on customizations/README.md
> +- The configuration file `customizations.yaml` will be composed with keys and their value, please do not define the same key several times, because they will be overridden between them. Each key in t
for _different_ configurations

2022-06-08 14:45 UTC, miguelangelmorenochacon approved these changes
🇺🇸

2022-06-08 14:53 UTC, alvarorm22 reviewed
:+1:

2022-06-08 15:12 UTC, jvillarf approved these changes

2022-06-08 15:15 UTC, merged