Custom buckets docs
CartoDB/carto-selfhosted-helm pull request #176
Opened 2022-06-21 14:51 UTC by alberhander

https://app.shortcut.com/cartoteam/story/238580/test-and-fix-aws-azure-buckets-with-private-thumbnails

2022-06-22 10:22 UTC, aitorch approved these changes

2022-06-22 11:20 UTC, jvillarf requested changes

2022-06-22 11:20 UTC, jvillarf commented on customizations/README.md
> +For each CARTO self hosted installation, we create and provide a Google Cloud Platform Service Account key that the CARTO backend uses to authenticate requests to Google APIs.
let's add -> `CARTO deploys a dedicated infrastructure for every self hosted installation and such Service Account key is required to use some of the services deployed`.

2022-06-22 11:20 UTC, jvillarf commented on customizations/README.md
> +TODO: Add the code related to Terraform
Instead of the code, just add a link to the proper `.tf` file in `carto-selfhosted/terraform/examples`

2022-06-22 11:20 UTC, jvillarf commented on customizations/README.md
> +   TODO: Add the code related to Terraform
Instead of the code, just add a link to the proper `.tf` file in `carto-selfhosted/terraform/examples`

2022-06-22 11:20 UTC, jvillarf commented on customizations/README.md
> +   ```
Missing the link to the terraform configuration for azure

2022-06-22 11:20 UTC, jvillarf commented on customizations/README.md
> +
Typo, these are the instructions for the docker-compose version

2022-06-22 15:16 UTC, jvillarf approved these changes

2022-06-23 09:23 UTC, jvillarf approved these changes

2022-06-23 11:05 UTC, merged