Feat/sc 234435/set jwt secret to selfhosted tenants
CartoDB/carto-selfhosted-helm pull request #197
Opened 2022-06-24 09:08 UTC by alvarorm22

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

2022-06-24 10:26 UTC, alvarorm22 commented
https://app.shortcut.com/cartoteam/story/234435/maps-api-v3-jwt-secret-is-not-being-configured-in-selfhosted

2022-06-27 12:30 UTC, jvillarf submitted a review, later dismissed

2022-06-27 12:54 UTC, ManuelLR requested changes

2022-06-27 12:54 UTC, ManuelLR commented on chart/templates/import-api/secret.yaml
> +  "IMPORT_JWT_SECRET"
This should be added also in a couple of additional places in the deployment (For all component/secrets)

2022-06-28 06:08 UTC, jvillarf approved these changes

2022-06-28 09:16 UTC, merged