node_options process assignment refactor
CartoDB/carto-selfhosted-helm pull request #278
Opened 2022-10-17 09:40 UTC by alvarorm22

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

2022-10-17 13:29 UTC, alvarorm22 commented
https://app.shortcut.com/cartoteam/story/263922/include-node-options-in-selfhosted-components

2022-10-25 10:06 UTC, jvillarf commented
https://github.com/CartoDB/cloud-native/pull/9668/files

2022-10-25 10:51 UTC, jvillarf requested changes
A couple of suggestions to be aligned with https://github.com/CartoDB/cloud-native/wiki/Container-Resources

2022-10-25 10:51 UTC, jvillarf commented on chart/values.yaml
> +  defaultNodeProcessMaxOldSpace: 1536
```suggestion
  defaultNodeProcessMaxOldSpace: 1875
```

2022-10-25 10:51 UTC, jvillarf commented on chart/values.yaml
> +  defaultNodeProcessMaxOldSpace: 768
```suggestion
  defaultNodeProcessMaxOldSpace: 1020
```

2022-10-25 11:02 UTC, jvillarf approved these changes

2022-10-25 11:02 UTC, merged